// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeSi-CFNzLxdaLwTm1ab7Ukxd-YdKKgcs',
    appId: '1:541811076039:web:9b8b49fa46fe516e4b07e2',
    messagingSenderId: '541811076039',
    projectId: 'fir-demo-5e910',
    authDomain: 'fir-demo-5e910.firebaseapp.com',
    storageBucket: 'fir-demo-5e910.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjgVsJ3607Yl6tZ8FQfufF6CKP63bpYiQ',
    appId: '1:541811076039:android:16fc60f444d02c834b07e2',
    messagingSenderId: '541811076039',
    projectId: 'fir-demo-5e910',
    storageBucket: 'fir-demo-5e910.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm9VHE903AUDLYR2ENHhNzfXuzy1sKzOs',
    appId: '1:541811076039:ios:dbf86ac1977816bf4b07e2',
    messagingSenderId: '541811076039',
    projectId: 'fir-demo-5e910',
    storageBucket: 'fir-demo-5e910.appspot.com',
    iosClientId: '541811076039-0c5auu3m0rh1i6v83pc1sqpe7pagjvei.apps.googleusercontent.com',
    iosBundleId: 'com.example.songplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm9VHE903AUDLYR2ENHhNzfXuzy1sKzOs',
    appId: '1:541811076039:ios:dbf86ac1977816bf4b07e2',
    messagingSenderId: '541811076039',
    projectId: 'fir-demo-5e910',
    storageBucket: 'fir-demo-5e910.appspot.com',
    iosClientId: '541811076039-0c5auu3m0rh1i6v83pc1sqpe7pagjvei.apps.googleusercontent.com',
    iosBundleId: 'com.example.songplayer',
  );
}
